env:
  global:
    - secure: OW7zJxYtazZC9/uAKTHqUWW018bSIAbisH3/7aBRXROdFdVJmJrtBvwVbo394m+uWT3hWWfOGu2DAMPVwq38UVmmpPl5Yl2ZtJ6fzjRttS+UPHkJ9o1UjvWS0Zc27U0j6O33a5+IqwfvY5WYB5BHbI1vblzKUkXldf5jcdecaxmPJKxxdVECRYKeACpTKmut88VkPPmGxL1jFBDuGikZmG+5JGVRX3NC05/96lkxpzPSvhk3VUus83H9TgmQXlq3rd5E0TbRAX05ypxtL6Xa4x245qqUnxC6B8yx1PqOBj7wyS1YOTqw8du46CYDVTFbd5G3vu3ay+hrmCfvBN9ZteVbQOgfL+v0VZfNu3ikl0jBCwmkCYmqnA2MTEvQia/kAkMIXoDSh+jS+P4jbOJx0aKNya7t3DxpegWZpslUut4V48zEt83nyQ5fMuzplZtTphfOvLkc0MpPAI+5FQ6ynjJ7UutnDpbq7N6XCa9HnU0jkyLhZ6+UAM1jQAKTER6NB97Cfqw7YYLNmQEePOSyk8gYuh3DuqR9JdDeq8nVTl7ViqHXv11o2v57bFa9yQeniTApJrjxsEYsMqO7DKzHHERit0HP/FsrhayBUQkLVE4n5nAHKfruRO6AfjFUZRgzdX8jm8yiwiNGBflE8N9KErpvoxAqjyjGMwSVqJyCSvY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
