addons:
    apt:
        packages:
        - dos2unix
cache:
- pip
dist: xenial
env:
    global:
    -   secure: qkQscyIlZoR5bos7oWor5trFbcufR6H398ckBPj5QB3Bihu0GE3AYkUFsC4QP5ePCiX2LwQldk073Rv15C8gTD7sapAplff2+KJQD+hTWphZVzoLd6LQGISF8OjNMUARgbtQvOsK1kjYiqavgZHlFGHUzce3xh3R4j6L44DJcNq+92YfhKkZL0btQVc8epcQ4091Hxc31wgazQ00vpuHdZNfjSokCibZW3KHL1g58YFZfWfmgQJwxhUIK2x7rUUJp91T2VJ9OBdGk+CT/ItX38gHiJu/KltktW36y8RY4+c0Yi/rEm00ewJ+scnQ8WHYeuub5X45axbgSs/12MbpJXP+YcFPqKHPYXmemKLl/zGOYq/x3srSy2Jz8Uic9NX4zqtNT8F7MLNTmCXXZ0TM88PZcAkGterGu9Aap5e4M5gEmO+SDpg5xLgDPw5XXi/LLc/vLSsCPgdiRw6sDnWrETy47Y4AfytIkWiP1ueB8nBhlJEqprd6ARyGMWe15EqXpWKTvx//d2yiVr6HLlMsNtJ4mEs7RXQB8PJcdxqEOWMI42oX2djrKawCgeVl8zD8JxnZ2xnpqC3RBcjGkjTFPlos55LbpSU4uqvenYbkOex0HY9MYR6islA1aSv3+DEAtcAZAMkuYzepgE/IWrkjT1BEQS3s3fGjC/HY/4hy1LQ=
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    -   GIT_BRANCH: master
    -   UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    -   ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py
install:
- pip3 install --upgrade pip
- pip3 install requests
- pip3 install ultimate-hosts-blacklist-whitelist PyYaml
- if [[ ! -f .admin ]]; then wget "${UPDATE_LOCATION}" -o /dev/null -O update.py &&
    chmod +x update.py; else echo "No need to download/update update.py."; fi
- if [[ ! -f .admin ]]; then wget "${ADMINISTATION_LOCATION}" -o /dev/null -O administration.py
    && chmod +x administration.py; else echo "No need to download/update administration.py.";
    fi
language: python
matrix:
    fast_finish: true
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@funilrys.com
        - mitchellkrogza+ultimatehostsblacklist@gmail.com
python:
- '3.7'
script:
- python3 ./update.py
sudo: required
