env:
  global:
    - secure: gxkD87FX0T1Xs4UYZwJEzaXu8llPHf4RWHOLeyxO09mEvoVrDrymdmuhoMAuqUrdQV5nqwbciEDpNmaMtfqNKJ0gSNqCpOjZYOlV8NLB6DrgIbWBAlkwWVW+qGf+1cf4wLfFOFBztfk1gFTkYo12tQ8SC1gARIsDTjJYENv5HfifLbF/oAyrJakFLZEa4CLXOj1YwivIqp0Si5l1vSwBYBqAkeAXlc0WfGz5xwnKWuekBtzYgeesP5HazNPkwIvTiF1ra7uAZ4JQPHxRjWNocLfgkFr4sUjL2/bGoh4696NrVcm5wFP2yayJAxUb9d3xUcRxTam8kXJBr8axNqC//ppjxHpazX9650p3aLKBvyHEAFlpfsPNFjQ48LXWDeoXdua9rDUz57cc6w43gh9jjxly0FgwYovN+/+ed3AT5rRSS/qfPnuyvUJSsv4P0zvNVm5gg7+Dd7AIz6ry/I8QDIaHhRaAMWWXFk1bbS+fMd2VVwK67j5OQewF0+BuovU3NZLXh4wlKLOFg+iSm7elqcgFTPqgTWd9TAp7l17Nr9xAjwl36uA8gbkwVdKYA4Kv+uJGORTwVLMSsuA9Vkl62BcfFe8baAUNUOQJyCc6PclbtU8uQn5j93JLoLIyOPajDN78650e6y7pnlVpfJnr6TAI4stQY4YEuXZkTx7WV74=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
