env:
  global:
    - secure: TMkMBqptMPawAE4ofD/xIuBbhC/15Dth67ARSltRtB1fVxNE9nt7UQmgePL26CE2G8284GYUUYQpyAIwyTzmgAbgOL0/TijIWbUg/B4uilOFOS23c/J0NNpxEbpwrzc4rGMZKFl53RggAVrkDmm7ggfdOyFQhQjQhUNPKBwxu9P7wk5E+vt0HIABY9OSOdQm9PRbOrxsoZHo9pjs94fTqf4YTFgdMEycoUfH0/3WdhyeyYCHn2M41Uh0jqC1vPdl0FxK3Lk4Kk86/3B74Lfp3Ey3EtO6ZFYMmuBfmfvbrCwpOqIHlZaH3zQ2Y74/kG1ZlQovfQfV3JlD7XVfJw1j8b6xTYFCLuftdOD7/6qrT+qVxf6gZbPAsWjttorcfzVHuFQfLj5orl1+qNIJXPNr9O7nH6aXGUf5t2iRwZ3N9IxUekHbvNpqhmglZwesfY5+pbgvqMBngmJqBFhozkOVSgMeLyQEWGLhzQH8hLgm7k7sZ63cecChTGbC75jQiD1jdvI/PyJWrzhzSvnrjRNqVpyif8xb9iJVd0v1H/HXeVR7yZomf9yt3Afi1Rspo4Z4AoDtRrHWKbwCdtR4Jm3bZx4DacpVsojfTDw4/Lx0HV8H0s903S29hwWEMFHDSD7a0yIn/U1PF7Ao0yk6njigdxmxA2aD1M3q9ONRbrKRzRk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
