env:
  global:
    - secure: NRgkZJSIkB1PibbhLHOnvp+73QAT99RpWcWIPZeuvFq6cgP9zxfydcxi+hOXF0UG4DoGEXR6fDAQClFy5TeBpvuOkm95/Mbb1L89hAYwVPezdBbn/OmrBHuDFt6T1kzb+ecM/pTvPjE1JSPK029+MXEbust2Gh65vXTO/MX/+tW/65w5dHWQiwDZf8x53P2gW/FEcQ9Ya8KQmiWARDSmFddxZtBS2t2DpXB5Ah2LoAATCRvAMpRAj2xYsmUJIbVVylODJoWu0zjJUkSDG3OpfPWzjIrXaHdsDCLwiw32y4gcTu5aY8ytDlcFg5lRWfm0QTsIckCQaJWr0uhJyE5YTLRJNaVK+2p08PItczSC4ousfiRJCmaJPyZu7EgW+UOp4XP94a7ue96o+AGZ2PbRUfOrzE9H4dhFF1TMLI9enqPVbCrFKfi/VsPg/WibRfgaH8MA3QGLPwvz/2OtNF9lkpl5CeWpmk8HD/ULBxHvf37FJK0H2k3ZuqyvQQstO/4bZCGfk5YqIIs1CktMgzeSaDkeTk5LoNErHMdGSLg6kk5WZhfAIStbq1j0MMdYg5iDuhX4NFsfw9YAZhcGBDruelH12qjSNUxst+nvbn/4+Jk0YzxuJv1RN240nGv5936FY9sI+lvPWYkoW67EzG58JoaVtALID4QsjFrdOuy8eJ0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
