env:
  global:
    - secure: gp+3wn0L8JsbgqaPbKjIiGFbpODjfZzAEghd82v1uzgp8kFB3qXs0jIc9s4VR0wJQxbDDbp3ULR5rXT8uG9oPo76r0nyq8adl5vvbzqD/luJoH+srbe/6vcdyBuSh0UHUGp9K9UeIoiP9DwZgXU+RDFvjf0tUqnuvRgSFBt+M9YIKiZjlEgOyLv3dPcakvCzsfMF1YERW8UZs3Cgx/9KjD+36gs5FrYJt7iOhtriXtylHwv+x31ouLqnLTeImZNZUl1ciDFlxsGVJxsRNDrYpMqvQVXHZgM8y1sfSXLV0QSaa/m1rO+BFJ4ihJvKRJLhGWMcVFx8OL7/f0RR/YlpgiNQa0IQSSKL0nlk2KlXxu4uGAL/GU0/ukE8ZN1uBMQNHVweDQJoQTX6X70tYPc0B6Bnn4JTXzIn259DJ3c1ffwWw8ra4L77PsX84xHoADPUe0ydbSjXQPQH3ezVmC9WfxGAiQavd5gGnV+kThH8PYDtm3gp4tKzNlH45wGaqJPa+Xw5M8MGMoXZbTV97GGYjQxBFhI9i74kyXivd9Xp35tWXmWVZ79Ia22pri9g2jkcLWCiz0tilQhn3z4mh9w38gGOKfDXl7XZpTN5ZmmL0kqHxVIISAaP58KKY5UTKGtuRmAmFoGuSX6k5JmvFaWyTwKzBerrbS7UyofjUmMhcTI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Mitchell_Krog_Snooping_IPS
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
